# Generated by Django 3.2 on 2021-11-29 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_initial'),
        ('main', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Склад с таким именем уже существует'}, max_length=200, unique=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'списки',
            },
        ),
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Категория к складу с таким именем уже существует'}, max_length=250, unique=True, verbose_name='Название')),
                ('unit', models.CharField(choices=[('литр', 'литр'), ('штук', 'штук'), ('килограмм', 'килограмм')], max_length=10, verbose_name='единица измерений')),
            ],
        ),
        migrations.CreateModel(
            name='ListName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Такое наименование уже существует'}, max_length=250, unique=True, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.categoryname', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('sum', models.FloatField(default=0.0)),
                ('type', models.IntegerField(choices=[(1, 'Приходник'), (2, 'Расходник'), (3, 'Перемещение')], verbose_name='Тип')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='warehouse.addlist')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route', verbose_name='ID рейса')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='warehouse.addlist')),
                ('wh_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.articles')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOperationInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0.0, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.categoryname', verbose_name='Категория')),
                ('inner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouseoperation')),
                ('name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='warehouse.listname')),
            ],
        ),
    ]
