# Generated by Django 3.2 on 2021-11-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('route', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessalary',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.direction', verbose_name=''),
        ),
        migrations.AddField(
            model_name='servicessalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='servicessalary',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.salary'),
        ),
        migrations.AddField(
            model_name='salaryinner',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='salaryinner',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.salary'),
        ),
        migrations.AddField(
            model_name='salarycurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.currency'),
        ),
        migrations.AddField(
            model_name='salarycurrency',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.salary'),
        ),
        migrations.AddField(
            model_name='salary',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.currency'),
        ),
        migrations.AddField(
            model_name='operationsinner',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agentofclient'),
        ),
        migrations.AddField(
            model_name='operationsinner',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.articles'),
        ),
        migrations.AddField(
            model_name='operationsinner',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AddField(
            model_name='operationsinner',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='operationsinner',
            name='inner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.operations'),
        ),
        migrations.AddField(
            model_name='operationsinner',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
