# Generated by Django 3.2 on 2021-11-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debits', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('financial', '0002_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operations',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agentofclient'),
        ),
        migrations.AddField(
            model_name='operations',
            name='agentClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debits.clientcontragents'),
        ),
        migrations.AddField(
            model_name='operations',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.articles', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='operations',
            name='cash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='financial.cashbox'),
        ),
        migrations.AddField(
            model_name='operations',
            name='cash_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_sender', to='financial.cashbox'),
        ),
        migrations.AddField(
            model_name='operations',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AddField(
            model_name='operations',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='operations',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='operations',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
