# Generated by Django 3.2 on 2021-11-29 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 17, 40, 51, 954343), verbose_name='Дата'),
        ),
    ]
