# Generated by Django 3.2 on 2021-11-29 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_operations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 17, 41, 29, 644456), verbose_name='Дата'),
        ),
    ]
