# Generated by Django 3.2 on 2021-11-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('route', '0001_initial'),
        ('main', '0002_initial'),
        ('debits', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptiontransmission',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receptiontransmission',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='main.client', verbose_name='Грузополучатель'),
        ),
        migrations.AddField(
            model_name='receptiontransmission',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.registration', verbose_name='Место оформления'),
        ),
        migrations.AddField(
            model_name='receptiontransmission',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route', verbose_name='ID рейса'),
        ),
        migrations.AddField(
            model_name='receptiontransmission',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender1', to='main.client', verbose_name='Грузоотправитель'),
        ),
        migrations.AddField(
            model_name='productp',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='productp',
            name='recTranID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.receptiontransmission'),
        ),
        migrations.AddField(
            model_name='price',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.direction', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='price',
            name='servicePrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.serviceprice'),
        ),
        migrations.AddField(
            model_name='packer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='упаковщик'),
        ),
        migrations.AddField(
            model_name='packer',
            name='id_REC_TRAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.receptiontransmission'),
        ),
        migrations.AddField(
            model_name='numberofplaces',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debits.clientcontragents'),
        ),
        migrations.AddField(
            model_name='numberofplaces',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AddField(
            model_name='numberofplaces',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='loader',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='loader',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='досмотрщик'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='id_REC_TRAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.receptiontransmission'),
        ),
        migrations.AlterUniqueTogether(
            name='packer',
            unique_together={('employee', 'id_REC_TRAN')},
        ),
        migrations.AlterUniqueTogether(
            name='inspector',
            unique_together={('employee', 'id_REC_TRAN')},
        ),
    ]
