# Generated by Django 3.2 on 2021-11-29 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContrAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(error_messages={'required': 'Поле обязательно для заполнения', 'unique': 'Контрагент с таким именем уже существует'}, max_length=100, unique=True, verbose_name='ID клиента')),
                ('store', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('more_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDebits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('sum', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDebitsInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(blank=True, max_length=100, null=True, verbose_name='Чек')),
                ('sum', models.FloatField(error_messages={'required': 'Поле обязательно для заполнения'}, verbose_name='Сумма')),
            ],
        ),
    ]
