# Generated by Django 3.2 on 2021-11-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('debits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedebitsinner',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='incomedebitsinner',
            name='inner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debits.incomedebits'),
        ),
    ]
