# Generated by Django 3.2 on 2021-11-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debits', '0002_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedebitsinner',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route', verbose_name='Рейс'),
        ),
    ]
