# Generated by Django 3.2 on 2021-11-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('financial', '0002_initial'),
        ('route', '0001_initial'),
        ('debits', '0003_incomedebitsinner_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedebits',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomedebits',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debits.clientcontragents', verbose_name='Контаргент'),
        ),
        migrations.AddField(
            model_name='incomedebits',
            name='cashBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.cashbox', verbose_name='Касса'),
        ),
        migrations.AddField(
            model_name='incomedebits',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='incomedebits',
            name='wh_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.articles', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='clientcontragents',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientcontragents',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
